server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://136.65.46.225:3306/helpdesk_dev
    username: helpdesk_user
    password: Gcp@2024

jwt:
  secret: i27academy-secret-key-which-is-32chars
  expiryMillis: 3600000
